const canvas=document.getElementById('stars'),ctx=canvas.getContext('2d');let stars=[];function resize(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);stars=Array.from({length:Math.min(170,Math.floor(innerWidth/8))},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:Math.random()*1.2+.15,a:Math.random()*.7+.15,s:Math.random()*.008+.002}))}function draw(t){ctx.clearRect(0,0,innerWidth,innerHeight);for(const s of stars){ctx.globalAlpha=s.a*(.65+.35*Math.sin(t*s.s));ctx.fillStyle='#d9efff';ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,Math.PI*2);ctx.fill()}requestAnimationFrame(draw)}addEventListener('resize',resize);resize();requestAnimationFrame(draw);

const info={core:['REGINE / ENGINEER','I build across application, automation and infrastructure layers — with code as the connecting thread.'],software:['SOFTWARE ENGINEERING','Full-stack applications and prototypes using React, Python, Java, JavaScript and APIs.'],ai:['AI ENGINEERING','LLM integrations, RAG, NLP, classification and rapid AI prototyping.'],devops:['DEVOPS','CI/CD, deployment automation, GitLab, Jenkins and security controls that move code safely.'],cloud:['CLOUD & CONTAINERS','AWS, Azure, Kubernetes, Docker and containerised systems from application to infrastructure.'],iac:['INFRASTRUCTURE AS CODE','Terraform and Ansible for repeatable provisioning, configuration, hardening and operations.'],platform:['PLATFORM ENGINEERING','RHEL, Ansible Automation Platform, Terraform Enterprise and enterprise integration patterns.'],data:['DATA & OBSERVABILITY','PostgreSQL, Firebase, ELK and data flows supporting applications and operational visibility.']};
const links=[['core','software'],['core','ai'],['core','devops'],['core','cloud'],['core','iac'],['core','platform'],['core','data'],['software','ai'],['devops','iac'],['devops','platform'],['cloud','iac'],['data','software']];
const group=document.getElementById('connections');for(const [a,b] of links){const A=document.querySelector('[data-node='+a+']'),B=document.querySelector('[data-node='+b+']');const line=document.createElementNS('http://www.w3.org/2000/svg','line');line.dataset.a=a;line.dataset.b=b;line.setAttribute('x1',A.style.getPropertyValue('--x')+'%');line.setAttribute('y1',A.style.getPropertyValue('--y')+'%');line.setAttribute('x2',B.style.getPropertyValue('--x')+'%');line.setAttribute('y2',B.style.getPropertyValue('--y')+'%');group.appendChild(line)}
const detail=document.getElementById('mapDetail');document.querySelectorAll('.node').forEach(n=>{n.setAttribute('aria-pressed','false');n.addEventListener('click',()=>{document.querySelectorAll('.node').forEach(x=>{x.classList.toggle('active',x===n);x.setAttribute('aria-pressed',String(x===n))});document.querySelectorAll('.lines line').forEach(l=>l.classList.toggle('active',l.dataset.a===n.dataset.node||l.dataset.b===n.dataset.node));const d=info[n.dataset.node];detail.querySelector('strong').textContent=d[0];detail.querySelector('p').textContent=d[1]})});
const reveal=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.animate([{opacity:0,transform:'translateY(24px)'},{opacity:1,transform:'none'}],{duration:650,easing:'cubic-bezier(.2,.7,.2,1)',fill:'both'})}),{threshold:.12});document.querySelectorAll('.project,.timeline article,.section-head').forEach(x=>reveal.observe(x));
document.querySelectorAll('.project-filter button').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.project-filter button').forEach(b=>{b.classList.toggle('active',b===btn);b.setAttribute('aria-pressed',String(b===btn))});const f=btn.dataset.filter;document.querySelectorAll('.project').forEach(p=>p.classList.toggle('is-hidden',f!=='all'&&p.dataset.kind!==f))}));
document.getElementById('themeToggle')?.addEventListener('click',e=>{document.body.classList.toggle('bright-stars');e.currentTarget.setAttribute('aria-pressed',String(document.body.classList.contains('bright-stars'))) });

const sections=[...document.querySelectorAll('main section[id]')],navLinks=[...document.querySelectorAll('.nav nav a')];
const navObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){navLinks.forEach(a=>a.classList.toggle('current',a.getAttribute('href')==='#'+e.target.id))}}),{rootMargin:'-35% 0px -55% 0px'});sections.forEach(s=>navObserver.observe(s));

const menuToggle=document.getElementById('menuToggle'),siteNav=document.getElementById('siteNav');
menuToggle?.addEventListener('click',()=>{const open=siteNav.classList.toggle('open');menuToggle.setAttribute('aria-expanded',String(open));menuToggle.setAttribute('aria-label',open?'Close navigation':'Open navigation')});
siteNav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{siteNav.classList.remove('open');menuToggle?.setAttribute('aria-expanded','false')}));
