import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import{Github,Mail,ExternalLink,ArrowDown,Menu,X,Terminal,BrainCircuit,CloudCog,Code2}from'lucide-react';import'./styles.css';

const projects=[
{n:'01',kind:'AI / FULL STACK',title:'JARMS — Emergency Audio Triage',desc:'AI-assisted emergency audio triage. Parallel agents analyze speech, situational audio and acoustic events before a central triage engine produces urgency, summaries and responder recommendations.',tech:['React','FastAPI','Supabase','OpenAI','Qwen'],proof:['3 AI agents','~20s processing','5 urgency tiers'],repo:'https://github.com/regyap/Project-JARMS',type:'ai'},
{n:'02',kind:'DEVTOOLS / IaC',title:'InfraFlow',desc:'Visual builder for Ansible and Terraform workflows with infrastructure-code generation, server-side validation and an interactive Three.js topology view.',tech:['Node.js','Ansible','Terraform','Three.js','AWS','Azure'],proof:['2 IaC formats','3D topology','AWS + Azure validation'],repo:'https://github.com/regyap/infraflow',type:'platform'},
{n:'03',kind:'AWS / EVENT-DRIVEN',title:'ROSA / GitLab Platform Foundation',desc:'Staged AWS platform foundation using Terraform, VPC networking, S3, DynamoDB idempotency, EventBridge, SQS FIFO/DLQ, API Gateway and Lambda.',tech:['Terraform','AWS','Lambda','EventBridge','SQS','DynamoDB'],repo:'https://github.com/regyap/projecta',type:'platform'},
{n:'04',kind:'AI / RAG',title:'AI Job Applicator',desc:'Resume comparison and job-matching system combining skill extraction and RAG-powered feedback with React and hybrid PostgreSQL/Firebase storage.',tech:['React','Python','PostgreSQL','Firebase','RAG','AWS'],type:'ai'},
{n:'05',kind:'PLATFORM / DEVSECOPS',title:'Enterprise Platform Automation',desc:'Reusable automation for RHEL hardening, agent installation and VM provisioning with DevSecOps controls across Ansible and Terraform workflows.',tech:['Ansible','Terraform','GitLab CI','RHEL','Podman'],type:'platform'}];

const experience=[['2025 — NOW','NCS','Infrastructure Engineer · Nucleus Graduate Program','Platform engineering, Linux hardening, DevSecOps pipelines, infrastructure automation and containerised enterprise platforms.'],['2024','Accenture','Cloud DevOps / Technical Architecture Intern','AWS operations, deployment automation, GitLab workflows, system administration and vulnerability remediation.'],['2022 — 2023','Ministry of Home Affairs','AI Developer / Software Engineering Intern','Full-stack AI prototypes, LLM integrations, operational dashboards and ML deployment.'],['2020 — 2021','Monetary Authority of Singapore','Software / Network Engineer Intern','ELK observability, Jenkins automation, Selenium testing and Python infrastructure auditing.']];

function App(){const[filter,setFilter]=useState('all'),[menu,setMenu]=useState(false),[active,setActive]=useState('software');
useEffect(()=>{const fn=()=>setMenu(false);addEventListener('resize',fn);return()=>removeEventListener('resize',fn)},[]);
const skills={software:['Software','React · Python · Java · JavaScript','I build applications and prototypes, then follow them down the stack when needed.'],ai:['AI','LLMs · RAG · NLP · Agents','AI is useful when it is part of a complete system: data, APIs, evaluation and human workflows.'],devops:['DevOps','GitLab · Jenkins · CI/CD','I automate delivery and repetitive operations instead of treating deployment as an afterthought.'],cloud:['Cloud / Platform','AWS · Azure · Kubernetes · Linux','I work with the infrastructure underneath applications so the system can actually run and be operated.']};
return <><a className="skip" href="#work">Skip to work</a><header><a className="logo" href="#">RY<span>.</span></a><nav className={menu?'open':''}>{['work','skills','experience','about'].map(x=><a key={x} href={'#'+x} onClick={()=>setMenu(false)}>{x}</a>)}</nav><div className="headActions"><a className="iconLink" href="https://github.com/regyap" target="_blank" aria-label="GitHub"><Github size={17}/></a><button className="menu" onClick={()=>setMenu(!menu)} aria-expanded={menu}>{menu?<X/>:<Menu/>}</button></div></header>
<main><section className="hero"><div className="eyebrow"><i/> SINGAPORE · SOFTWARE / AI / DEVOPS / CLOUD</div><h1>I build the <em>system,</em><br/>not just the <span>layer.</span></h1><p>I'm Regine Yap. I move between application code, AI systems, automation and the infrastructure underneath them — turning prototypes into systems that can actually run.</p><div className="actions"><a className="primary" href="#work">Explore selected work <ArrowDown size={15}/></a><a href="https://github.com/regyap" target="_blank">GitHub <ExternalLink size={13}/></a></div><div className="signals"><div><Code2/><b>BUILD</b><span>apps + AI prototypes</span></div><div><Terminal/><b>AUTOMATE</b><span>delivery + infrastructure</span></div><div><CloudCog/><b>OPERATE</b><span>production platforms</span></div></div></section>
<section id="work" className="section"><Heading k="01 / SELECTED BUILDS" title="Evidence over buzzwords." sub="Projects selected for implementation depth, range and inspectable engineering decisions."/><div className="filters">{[['all','ALL'],['ai','SOFTWARE / AI'],['platform','DEVOPS / PLATFORM']].map(([v,l])=><button className={filter===v?'active':''} onClick={()=>setFilter(v)} aria-pressed={filter===v} key={v}>{l}</button>)}</div><div className="projects">{projects.filter(p=>filter==='all'||p.type===filter).map(p=><article className="project" key={p.n}><span className="num">{p.n}</span><div><small>{p.kind}</small><h3>{p.title}</h3><p>{p.desc}</p>{p.proof&&<div className="proof">{p.proof.map(x=><b key={x}>{x}</b>)}</div>}<div className="tech">{p.tech.map(x=><span key={x}>{x}</span>)}</div>{p.repo&&<a className="repo" href={p.repo} target="_blank">VIEW SOURCE <ExternalLink size={12}/></a>}</div></article>)}</div></section>
<section id="skills" className="section skills"><Heading k="02 / ENGINEERING MAP" title="One engineer. Multiple layers." sub="Select a layer to see how I think about it."/><div className="skillLayout"><div className="skillTabs">{Object.entries(skills).map(([k,v])=><button key={k} className={active===k?'active':''} onClick={()=>setActive(k)}><span>{v[0]}</span><small>{v[1]}</small></button>)}</div><div className="skillDetail"><BrainCircuit/><span>SELECTED LAYER</span><h3>{skills[active][0]}</h3><p>{skills[active][2]}</p></div></div></section>
<section id="experience" className="section"><Heading k="03 / EXPERIENCE" title="From code to production."/><div className="timeline">{experience.map(e=><article key={e[0]+e[1]}><time>{e[0]}</time><div><h3>{e[1]}</h3><b>{e[2]}</b><p>{e[3]}</p></div></article>)}</div></section>
<section id="about" className="about"><span>04 / ABOUT</span><div><h2>Software and infrastructure shouldn't be separate worlds.</h2><p>My background crosses software engineering, AI, networking and infrastructure. I use that range to understand systems end to end, automate what repeats, and keep learning far enough down the stack to understand why things work.</p><p>Outside work I keep building through projects, LeetCode, hackathons and cloud/platform labs.</p><div className="contact"><a href="mailto:regineyap1609@gmail.com"><Mail size={15}/> EMAIL ME</a><a href="https://github.com/regyap" target="_blank"><Github size={15}/> GITHUB</a></div></div></section></main><footer><span>REGINE YAP © 2026</span><span>BUILD · AUTOMATE · OPERATE</span></footer></>}
function Heading({k,title,sub}){return <div className="heading"><span>{k}</span><h2>{title}</h2>{sub&&<p>{sub}</p>}</div>} }createRoot(document.getElementById('root')).render(<App/>);